# Generated by Django 5.2.1 on 2025-05-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_type',
            field=models.CharField(choices=[('BLOOD', 'Blood Test'), ('URINE', 'Urine Test'), ('IMAGING', 'Imaging'), ('PATHOLOGY', 'Pathology'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='labtest',
            name='urgency',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=10),
        ),
    ]
