# Generated by Django 5.2.1 on 2025-05-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0004_role_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.IntegerField(default=1),
        ),
    ]
